/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ndk_NDK_Methods */

#ifndef _Included_ndk_NDK_Methods
#define _Included_ndk_NDK_Methods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ndk_NDK_Methods
 * Method:    SayHelo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ndk_NDK_1Methods_SayHelo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
